### ISSUE TITLE
Add a linter

### ISSUE THREAD

**Issue by WarrenWongCodes** [WarrenWongCodes/the-tech-interview#6]
# Current Behavior

We are missing a linter. ESLint

## Context

- Add ESLint dependency
- Add associating ESlint configuration file
- Ensure linting is working
- Run lint and fix all errors

**Comment by Vinitvh** [comment]
Hi, I would like to work on this.

**Comment by WarrenWongCodes** [comment]
@Vinitvh Great. You can submit a Pull Request and assign it to me.
